DjangoGramm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views
from DjangoGramm.settings import (
    MEDIA_URL,
    MEDIA_ROOT,
    DEBUG,
)

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
    path("auths/", include("auths.urls")),
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("allauth/", include("allauth.urls")),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler404 = "DjangoGramm.views.handler404"

auths/urls.py
from django.urls import path, re_path

from . import views

app_name = "auths"
urlpatterns = [
    path("login/", views.AuthsLoginView.as_view(), name="login"),
    path("logout/", views.AuthsLogoutView.as_view(), name="logout"),
    path("signup/", views.AuthsSignupView.as_view(), name="signup"),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        views.AuthsConfirmEmailView.as_view(),
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        views.EmailVerificationSentView.as_view(),
        name="account_email_verification_sent",
    ),
]

auths/models.py
from django.contrib.auth.models import AbstractUser
from django.apps import apps
from django.db import models


class User(AbstractUser):
    email = models.EmailField(blank=True, null=True, default=None, unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        UserProfile = apps.get_model("accounts", "UserProfile")

        if not hasattr(self, "userprofile"):
            UserProfile.objects.create(user=self)

auths/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

from auths.models import User


class EmailOnlyRegistrationForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["email"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="login")
    password = forms.CharField(label="password", widget=forms.PasswordInput)


class UserForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

auths/views.py
from allauth.account.views import (
    LoginView,
    SignupView,
    LogoutView,
    ConfirmEmailView,
)
from django.views.generic import TemplateView


class AuthsSignupView(SignupView):
    template_name = "auths/signup.html"


class AuthsLoginView(LoginView):
    template_name = "auths/login.html"


class AuthsLogoutView(LogoutView):
    template_name = "auths/logout.html"


class AuthsConfirmEmailView(ConfirmEmailView):
    template_name = "auths/email_confirm.html"


class EmailVerificationSentView(TemplateView):
    template_name = "auths/verification_sent.html"

auths/templates/auths/email_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_filters %}
{% load account %}


{% block head_title %}
    {% trans "Confirm Email Address" %}
{% endblock head_title %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-6 mx-auto">
                <div class="card p-3">
                    <div class="card-title text-center">
                        <h3>
                            {% trans "Confirm Email Address" %}
                        </h3>
                    </div>
                    <div class="card-body text-center">
                        {% if confirmation %}
                            {% user_display confirmation.email_address.user as user_display %}
                            {% if can_confirm %}
                                <p>
                                    {% blocktrans with confirmation.email_address.email as email %}
                                        Please confirm that
                                        <a href="mailto:{{ email }}">{{ email }}</a>
                                        is an email
                                        address for user {{ user_display }}
                                    {% endblocktrans %}
                                </p>
                                {% url 'auths:account_confirm_email' confirmation.key as action_url %}
                                <form method="post"
                                      action="{% url 'auths:account_confirm_email' confirmation.key as action_url %}">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit"
                                            class="btn btn-primary">
                                        Confirm
                                    </button>
                                </form>
                            {% else %}
                                <p>
                                    {% blocktrans %}Unable to confirm
                                        {{ email }}
                                        because it is
                                        already confirmed by a different
                                        account.{% endblocktrans %}
                                </p>
                            {% endif %}
                        {% else %}
                            {% url 'account_email' as email_url %}
                            <p>
                                {% blocktrans %}This email confirmation link
                                    expired
                                    or is invalid.
                                    Please
                                    <a href="{{ email_url }}">issue a new email
                                        confirmation
                                        request</a>.{% endblocktrans %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

auths/templates/auths/login.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-12 col-md-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center">Log in</h3>
                        <form method="post" action="{% url 'auths:login' %}">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary">Log
                                in
                            </button>
                        </form>
                        <hr>
                        <p class="text-center">Or log in with:</p>
                        <p class="text-center"><a
                                href="{% provider_login_url 'google' %}"
                                class="btn btn-danger me-5"><i class="fa-brands fa-google"></i> Google</a><a
                                href="{% provider_login_url 'github' %}"
                                class="btn btn-secondary"><i class="fa-brands fa-github"></i> Github</a>
                        </p>
                        {% providers_media_js %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auths/templates/auths/logout.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load allauth i18n %}

{% block content %}
    <div class="container mt-5 d-flex justify-content-center">
        <div class="card text-center p-3">
            <h2 class="card-title mx-auto">Log Out</h2>
            <div class="card-body">
                <p>Do you wanna to leave us</p>
                <form class="" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Yep, I`m done
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auths/templates/auths/registration.html
{% extends "base.html" %}
{% block content %}
    <h1 class="center">Registration</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
    </form>
{% endblock %}

auths/templates/auths/signup.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-12 col-md-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center">Sign up</h3>
                        <form method="post" action="{% url 'auths:signup' %}">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary">Sign
                                up
                            </button>
                        </form>
                        <p class="text-center">Or log in with:</p>
                        <p class="text-center"><a
                                href="{% provider_login_url 'google' %}"
                                class="btn btn-danger me-5"><i
                                class="fa-brands fa-google"></i> Google</a><a
                                href="{% provider_login_url 'github' %}"
                                class="btn btn-secondary"><i
                                class="fa-brands fa-github"></i> Github</a>
                        </p>
                        {% providers_media_js %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auths/templates/auths/verification_sent.html
{% extends "base.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Verify Your Email Address" %}
{% endblock head_title %}
{% block content %}
    <div class="container mt-5">
        <h3>
            {% trans "Verify Your Email Address" %}
        </h3>
        <p>
            {% blocktrans %}We have emailed you for verification.
                Follow the link provided to finalize the signup process. If you
                do not see the verification email in your main inbox, check your
                spam folder. Please contact us if you do not receive the
                verification email within a few minutes.{% endblocktrans %}
        </p>
    </div>
{% endblock content %}