DjangoGramm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views
from DjangoGramm.settings import (
    MEDIA_URL,
    MEDIA_ROOT,
    DEBUG,
)

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
    path("auths/", include("auths.urls")),
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("allauth/", include("allauth.urls")),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler404 = "DjangoGramm.views.handler404"

auths/urls.py
from django.urls import path, re_path

from . import views

app_name = "auths"
urlpatterns = [
    path("login/", views.AuthsLoginView.as_view(), name="login"),
    path("logout/", views.AuthsLogoutView.as_view(), name="logout"),
    path("signup/", views.AuthsSignupView.as_view(), name="signup"),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        views.AuthsConfirmEmailView.as_view(),
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        views.EmailVerificationSentView.as_view(),
        name="account_email_verification_sent",
    ),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path(
        "<int:pk>/edit/",
        views.UpdatePost.as_view(),
        name="edit_post",
    ),
    path(
        "<int:pk>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path(
        "<int:pk>/delete/",
        views.DeletePost.as_view(),
        name="delete_post",
    ),
    path(
        "photos/<int:pk>/delete/",
        views.DeletePhoto.as_view(),
        name="delete_photo",
    ),
    path(
        "",
        views.PostsListView.as_view(),
        name="post_list",
    ),
    path(
        "following/",
        views.PostsFollowingListView.as_view(),
        name="post_following_list",
    ),
    path(
        "accounts/<int:user_id>/create/",
        views.CreatePostView.as_view(),
        name="create_post",
    ),
    path(
        "like/<int:pk>/",
        views.LikePostView.as_view(),
        name="like_post",
    ),
    path(
        "check_like/<int:pk>/",
        views.CheckLikeView.as_view(),
        name="check_like",
    ),
    path(
        "add_comment/<int:post_id>/",
        views.AddCommentView.as_view(),
        name="add_comment",
    ),
]

posts/models.py
from functools import partial

from cloudinary.models import CloudinaryField
from django.db import models
from django.db.models import UniqueConstraint

from DjangoGramm.settings import PICTURES
from DjangoGramm.utils import directory_path
from auths.models import User


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    caption = models.CharField(max_length=250)
    content = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    hashtags = models.ManyToManyField("Hashtag", blank=True)


class Photo(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="photos"
    )
    picture = CloudinaryField("picture")

    def delete(self, *args, **kwargs):
        file = self.picture
        super().delete(*args, **kwargs)
        file.delete(save=False)


class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)


class Like(models.Model):
    post = models.ForeignKey(
        "Post", related_name="likes", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=["post", "user"], name="user_like_post")
        ]


class Comment(models.Model):
    post = models.ForeignKey(
        "Post", related_name="comments", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    content = models.TextField(max_length=280, blank=False)

posts/forms.py
from django import forms
from cloudinary.forms import CloudinaryFileField

from posts.models import Post, Photo, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Post
        fields = ("caption", "content")


class PhotoForm(forms.ModelForm):
    picture = CloudinaryFileField()

    class Meta:
        model = Photo
        fields = ["picture"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].options = {"tags": "photo", "format": "png"}


class PhotoFormEdit(forms.ModelForm):
    picture = CloudinaryFileField(required=False)

    class Meta:
        model = Photo
        fields = ("picture",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].options = {"tags": "photo", "format": "png"}


class HashtagForm(forms.Form):
    hashtags = forms.CharField(max_length=50, required=False)


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="comment")

    class Meta:
        model = Comment
        fields = ("content",)

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, OuterRef, Exists, Prefetch
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpRequest, JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from auths.models import User
from posts.forms import (
    PostForm,
    PhotoForm,
    PhotoFormEdit,
    HashtagForm,
    CommentForm,
)
from posts.models import Post, Photo, Like, Comment
from DjangoGramm.text_messages import (
    POST_CREATED_SUCCESS_MSG,
    POST_CREATED_DENIED_MSG,
    POST_EDIT_SUCCESS_MSG,
    CREATE_POST_SUBMIT,
    UPDATE_POST_SUBMIT,
    BAD_REQUEST,
)
from posts.utils import hashtag_handler
from posts.mixins import UserIsOwnerMixin


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/create_post.html"

    def get_success_url(self):
        return f'{reverse_lazy("posts:post_list")}?user={self.request.user.pk}'

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        if self.kwargs.get("user_id") != self.request.user.pk:
            messages.error(self.request, POST_CREATED_DENIED_MSG)
            return redirect(self.request.META.get("HTTP_REFERER", "home"))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()

        photo_form = PhotoForm(self.request.POST, self.request.FILES)
        if photo_form.is_valid():
            photo = photo_form.save(commit=False)
            photo.post = post
            photo.save()

        hashtag_form = HashtagForm(self.request.POST)
        if hashtag_form.is_valid():
            hashtags = hashtag_form.cleaned_data.get("hashtags")
            if hashtags:
                hashtag_handler(post=post, hashtags=hashtags.split())

        messages.success(self.request, POST_CREATED_SUCCESS_MSG)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["photo_form"] = PhotoForm(
                self.request.POST, self.request.FILES
            )
            context["hashtag_form"] = HashtagForm(self.request.POST)
        else:
            context["photo_form"] = PhotoForm()
            context["hashtag_form"] = HashtagForm()
            context["submit_button"] = CREATE_POST_SUBMIT
            context["title"] = "Create"
        return context


class UpdatePost(UserIsOwnerMixin, LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/edit_post.html"

    def get_success_url(self):
        return f'{reverse_lazy("posts:post_list")}?user={self.request.user.pk}'

    def form_valid(self, form):
        photo_form = PhotoForm(self.request.POST, self.request.FILES)
        if photo_form.is_valid():
            photo = photo_form.save(commit=False)
            photo.post = self.object
            photo.save()

        hashtag_form = HashtagForm(self.request.POST)
        if hashtag_form.is_valid():
            hashtags = hashtag_form.cleaned_data.get("hashtags")
            if hashtags:
                hashtag_handler(post=self.object, hashtags=hashtags.split())
        messages.success(self.request, POST_EDIT_SUCCESS_MSG)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            context["photo_form"] = PhotoFormEdit(
                self.request.POST, self.request.FILES
            )
            context["hashtag_form"] = HashtagForm(self.request.POST)
        else:
            context["photo_form"] = PhotoFormEdit()
            context["hashtag_form"] = HashtagForm()
            context["submit_button"] = UPDATE_POST_SUBMIT
            context["title"] = "Update"
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = "post"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related("user__userprofile").prefetch_related(
            "photos", "hashtags", "likes"
        )


class PostsListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = "posts"

    def _get_query_params(self):
        hashtag = self.request.GET.get("hashtag")  # type: ignore
        user_id = self.request.GET.get("user")  # type: ignore
        return hashtag, user_id

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.GET.get("user")  # type: ignore

        if user_id:
            user = get_object_or_404(User, pk=user_id)
            context["profile_user"] = user
        context["feed_name"] = "All posts"
        context["comment_form"] = CommentForm()
        return context

    def get_template_names(self):
        hashtag, user_id = self._get_query_params()
        if user_id:
            return ["posts/user_posts.html"]
        else:
            return ["posts/feed.html"]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = (
            queryset.select_related("user", "user__userprofile")
            .prefetch_related("photos", "hashtags", "likes")
            .order_by("-created_at")
        )
        likes = Like.objects.filter(user=self.request.user, post=OuterRef("pk"))
        comment_prefetch = Prefetch(
            "comments",
            queryset=Comment.objects.select_related("user__userprofile"),
        )
        queryset = queryset.prefetch_related(comment_prefetch).annotate(
            user_like_it=Exists(likes)
        )
        hashtag, user_id = self._get_query_params()
        if hashtag:
            queryset = queryset.filter(hashtags__name=hashtag)
        elif user_id:
            try:
                user_id = int(user_id)
            except ValueError as ex:
                messages.error(BAD_REQUEST, ex)
                return redirect("home")
            queryset = queryset.filter(user__id=user_id)
        return queryset


class PostsFollowingListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = "posts/feed.html"
    context_object_name = "posts"

    def _get_followed_users(self):
        return User.objects.filter(followers__follower=self.request.user)

    def get_queryset(self):
        followed_users = self._get_followed_users()
        queryset = super().get_queryset()
        queryset = (
            queryset.filter(user__in=followed_users)
            .select_related("user__userprofile")
            .prefetch_related("photos", "hashtags", "likes")
            .prefetch_related(
                Prefetch(
                    "comments",
                    queryset=Comment.objects.select_related(
                        "user__userprofile"
                    ),
                )
            )
            .annotate(
                user_like_it=Exists(
                    Like.objects.filter(
                        user=self.request.user, post=OuterRef("pk")
                    )
                )
            )
            .order_by("-created_at")
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["feed_name"] = "Following"
        return context


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = get_object_or_404(Post, pk=post_id)
            comment.save()
            return JsonResponse(
                {
                    "status": "success",
                    "message": "Comment added",
                    "username": request.user.username,
                    "comment": comment.content,
                }
            )
        else:
            return JsonResponse({"status": "error", "message": "Invalid form"})


class DeletePost(UserIsOwnerMixin, LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        return f'{reverse_lazy("posts:post_list")}?user={self.request.user.pk}'


class DeletePhoto(UserIsOwnerMixin, LoginRequiredMixin, DeleteView):
    model = Photo

    def get_success_url(self):
        return self.request.META.get("HTTP_REFERER", "home")


class LikePostView(LoginRequiredMixin, View):
    def post(self, request, pk):
        response_data = {"liked": False, "likes_count": 0}
        post = get_object_or_404(Post, pk=pk)
        try:
            like = Like.objects.get(post=post, user=request.user)
            like.delete()
            response_data["liked"] = False
        except Like.DoesNotExist:
            Like.objects.create(post=post, user=request.user)
            response_data["liked"] = True
        response_data["likes_count"] = post.likes.count()
        return JsonResponse(response_data)


class CheckLikeView(LoginRequiredMixin, View):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        response_data = {"liked": False}
        try:
            Like.objects.get(post=post, user=request.user)
            response_data["liked"] = True

        except Like.DoesNotExist:
            pass
        return JsonResponse(response_data)

posts/templates/posts/includes/post_form.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<div class="container my-4">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ title }} Post</h2>
            <form method="post" enctype="multipart/form-data" class="row g-3">
                {% csrf_token %}
                {{ form|crispy }}
                {{ photo_form|crispy }}
                {{ hashtag_form|crispy }}
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">{{ submit_button }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

posts/templates/posts/includes/single_post.html
{% load static %}
{% load crispy_forms_filters %}
{% load cloudinary %}

<h6>{{ post.caption }}</h6>
{% if post.photos.all.count > 1 %}
    <div id="PostCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            {% for photo in post.photos.all %}
                <button type="button" data-bs-target="#PostCarousel"
                        data-bs-slide-to="{{ forloop.counter0 }}"
                        {% if forloop.first %}class="active"
                        aria-current="true"{% endif %}
                        aria-label="Slide {{ forloop.counter }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            {% for photo in post.photos.all %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <img src="{{ photo.picture.url }}" alt=""
                         class="img-fluid"
                         style="max-width: 100%; width: 550px; height: 550px; object-fit: cover;">
                </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button"
                data-bs-target="#PostCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"
                      aria-hidden="true"></span>
            <span class="visually-hidden">Prev</span>
        </button>
        <button class="carousel-control-next" type="button"
                data-bs-target="#PostCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon"
                      aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
{% else %}
    {% for photo in post.photos.all %}
        <img src="{{ photo.picture.url }}" alt=""
             class="img-fluid"
             style="max-width: 100%; width: 550px; height: 550px; object-fit: cover;">
    {% endfor %}
{% endif %}

<p>{{ post.content }}</p>
{% for hashtag in post.hashtags.all %}
    <a href="{% url 'posts:post_list' %}?hashtag={{ hashtag.name }}"><span
            class="hashtag">#{{ hashtag.name }}</span></a>
{% endfor %}
<p class="like-count"
   data-post-id="{{ post.pk }}">{{ post.likes.count }} likes</p>

<div class="d-flex mb-3">
    <button type="button" data-id="{{ post.pk }}"
            class="like-btn btn btn-lg custom-btn me-2">
        {% if post.user_like_it %}
            <i class="fa-solid fa-heart"
               style="color: #ff3040"></i>{% else %}
            <i class="fa-regular fa-heart"></i>{% endif %}
    </button>
    <a href="{% url 'posts:post_detail' post.pk %}"
       class="btn btn-lg custom-btn me-2"><i
            class="fa-solid fa-magnifying-glass"></i></a>
    {% if post.user == request.user %}
        <a href="{% url 'posts:edit_post' post.pk %}"
           class="btn btn-lg custom-btn me-2">
            <i class="fa-solid fa-gear"></i>
        </a>
    {% endif %}
</div>

<form class="comment-form" data-post-id="{{ post.id }}" method="post"
      action="{% url 'posts:add_comment' post.pk %}">
    {% csrf_token %}
    <div>{{ comment_form|crispy }}</div>
    <button type="button" class="submit-comment btn btn-primary small mb-3">Add
        Comment
    </button>
</form>

<div class="comments-container">
    {% for comment in post.comments.all %}
        <div class="row align-items-center">
            <div class="col-1 mb-auto"><a
                    href="{% url 'posts:post_list' %}?user={{ comment.user.id }}"><img
                    class="rounded-circle"
                    style="width: 30px; height: auto;"
                    src="{% if comment.user.userprofile.avatar %}{{ comment.user.userprofile.avatar.url }}{% else %}{% static 'images/no_avatar.jpg' %}{% endif %}"
                    alt=""></a></div>
            <div class="col-sm-11">
                <p style="font-size: small">
                    <b>{{ comment.user.username }}: </b>{{ comment.content }}
                </p>
                <p style="font-size: x-small; color: grey">
                    {{ comment.created_at }}
                </p>
            </div>
        </div>
    {% endfor %}
</div>