DjangoGramm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views
from DjangoGramm.settings import (
    MEDIA_URL,
    MEDIA_ROOT,
    DEBUG,
)

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
    path("auths/", include("auths.urls")),
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("allauth/", include("allauth.urls")),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler404 = "DjangoGramm.views.handler404"

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("<int:user_id>/", views.UserAccountView.as_view(), name="profile"),
    path("", views.UsersListView.as_view(), name="get_all_users"),
    path("<int:pk>/follow/", views.FollowUserView.as_view(), name="follow"),
    path(
        "<int:pk>/check_follow/",
        views.CheckFollowView.as_view(),
        name="check_follow",
    ),
    path(
        "following/",
        views.FollowingList.as_view(),
        name="following",
    ),
    path(
        "followers/",
        views.FollowersList.as_view(),
        name="followers",
    ),
]

auths/urls.py
from django.urls import path, re_path

from . import views

app_name = "auths"
urlpatterns = [
    path("login/", views.AuthsLoginView.as_view(), name="login"),
    path("logout/", views.AuthsLogoutView.as_view(), name="logout"),
    path("signup/", views.AuthsSignupView.as_view(), name="signup"),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        views.AuthsConfirmEmailView.as_view(),
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        views.EmailVerificationSentView.as_view(),
        name="account_email_verification_sent",
    ),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path(
        "<int:pk>/edit/",
        views.UpdatePost.as_view(),
        name="edit_post",
    ),
    path(
        "<int:pk>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path(
        "<int:pk>/delete/",
        views.DeletePost.as_view(),
        name="delete_post",
    ),
    path(
        "photos/<int:pk>/delete/",
        views.DeletePhoto.as_view(),
        name="delete_photo",
    ),
    path(
        "",
        views.PostsListView.as_view(),
        name="post_list",
    ),
    path(
        "following/",
        views.PostsFollowingListView.as_view(),
        name="post_following_list",
    ),
    path(
        "accounts/<int:user_id>/create/",
        views.CreatePostView.as_view(),
        name="create_post",
    ),
    path(
        "like/<int:pk>/",
        views.LikePostView.as_view(),
        name="like_post",
    ),
    path(
        "check_like/<int:pk>/",
        views.CheckLikeView.as_view(),
        name="check_like",
    ),
    path(
        "add_comment/<int:post_id>/",
        views.AddCommentView.as_view(),
        name="add_comment",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}DG{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Lobster&family=Montserrat:wght@400;700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/dev.css' %}">
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {#    <button onclick="history.back();" class="btn btn-secondary btn-sm"><i#}
    {#            class="fa fa-arrow-left"></i>#}
    {#    </button>#}
    <a class="navbar-brand ms-3" href="{% url 'home' %}">DjangoGramm</a>


    {% if request.user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto">
                <li><a class="nav-link me-3"
                       href="{% url 'accounts:profile' user_id=user.id %}"><i
                        class="fa-regular fa-user"></i> Profile</a>
                </li>
                <li><a class="nav-link me-3"
                       href="{% url 'posts:create_post' user.id %}"><i
                        class="fa-regular fa-square-plus"></i> Create
                    post</a></li>
                <li><a class="nav-link me-3"
                       href="{% url 'posts:post_list' %}?user={{ user.id }}"><i
                        class="fa-solid fa-house"></i> My
                    posts</a></li>
                <li><a class="nav-link me-3"
                       href="{% url 'posts:post_following_list' %}"><i
                        class="fa-solid fa-check-double"></i> Following</a></li>
                <li><a class="nav-link me-3"
                       href="{% url 'posts:post_list' %}"><i
                        class="fa-regular fa-images"></i> All posts</a></li>
                <li><a class="nav-link me-3"
                       href="{% url 'accounts:get_all_users' %}"><i
                        class="fa-regular fa-address-book"></i> Find
                    user</a>
                </li>
                <li><a class="nav-link ms-5 btn-logout"
                       href="{% url 'auths:logout' %}"><i
                        class="fa-solid fa-right-from-bracket"></i></a></li>
            </ul>

        </div>
    {% endif %}


</nav>
<body>
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert {% if 'error' in message.tags %}alert-danger{% elif 'success' in message.tags %}alert-success{% endif %}"
                 role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% block content %}
{% endblock %}
<script src="https://kit.fontawesome.com/d227c0280f.js"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'bundle.js' %}"></script>
</body>
</html>

templates/base_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {{ block.super }}
    <div class="row">
        <div class="col-md-2 d-none d-md-block align-items-center-center">
            <p class="d-flex flex-column align-items-center">
                <a href="{% url 'accounts:profile' user_id=user.id %}"><img
                        src="{% if user.userprofile.avatar %}
                        {{ user.userprofile.avatar.url }}
                        {% else %}{% static 'images/no_avatar.jpg' %}
                        {% endif %}"
                        alt="User Avatar"
                        class="rounded-circle"
                        style="width: 80%; max-width: 120px; height: auto;"></a>
            </p>
            <p class="d-flex flex-column align-items-center m-5">
                <a class="menu-btn" href="{% url 'accounts:following' %}"><i
                        class="fa-solid fa-person-running icon-size"
                        style="font-size: large"></i></a>
            </p>
            <p class="d-flex flex-column align-items-center m-5">
                <a class="menu-btn" href="{% url 'accounts:followers' %}"><i
                        class="fa-solid fa-users icon-size"></i></a></p>
        </div>
        <div class="col-lg-10 col-sm-10">
            {% block main %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}
    {{ block.super }} Home
{% endblock %}
{% block content %}
    <div class="d-flex flex-column align-items-center">
        <p class="mt-5">
            <a href="{% url 'auths:login' %}" class="btn btn-primary">login</a>
        </p>
        <p>
            <a href="{% url 'auths:signup' %}" class="btn btn-primary">registration</a>
        </p>
    </div>
{% endblock %}