DjangoGramm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views
from DjangoGramm.settings import (
    MEDIA_URL,
    MEDIA_ROOT,
    DEBUG,
)

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
    path("auths/", include("auths.urls")),
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("allauth/", include("allauth.urls")),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler404 = "DjangoGramm.views.handler404"

auths/urls.py
from django.urls import path, re_path

from . import views

app_name = "auths"
urlpatterns = [
    path("login/", views.AuthsLoginView.as_view(), name="login"),
    path("logout/", views.AuthsLogoutView.as_view(), name="logout"),
    path("signup/", views.AuthsSignupView.as_view(), name="signup"),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        views.AuthsConfirmEmailView.as_view(),
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        views.EmailVerificationSentView.as_view(),
        name="account_email_verification_sent",
    ),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path(
        "<int:pk>/edit/",
        views.UpdatePost.as_view(),
        name="edit_post",
    ),
    path(
        "<int:pk>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path(
        "<int:pk>/delete/",
        views.DeletePost.as_view(),
        name="delete_post",
    ),
    path(
        "photos/<int:pk>/delete/",
        views.DeletePhoto.as_view(),
        name="delete_photo",
    ),
    path(
        "",
        views.PostsListView.as_view(),
        name="post_list",
    ),
    path(
        "following/",
        views.PostsFollowingListView.as_view(),
        name="post_following_list",
    ),
    path(
        "accounts/<int:user_id>/create/",
        views.CreatePostView.as_view(),
        name="create_post",
    ),
    path(
        "like/<int:pk>/",
        views.LikePostView.as_view(),
        name="like_post",
    ),
    path(
        "check_like/<int:pk>/",
        views.CheckLikeView.as_view(),
        name="check_like",
    ),
    path(
        "add_comment/<int:post_id>/",
        views.AddCommentView.as_view(),
        name="add_comment",
    ),
]

posts/models.py
from functools import partial

from cloudinary.models import CloudinaryField
from django.db import models
from django.db.models import UniqueConstraint

from DjangoGramm.settings import PICTURES
from DjangoGramm.utils import directory_path
from auths.models import User


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    caption = models.CharField(max_length=250)
    content = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    hashtags = models.ManyToManyField("Hashtag", blank=True)


class Photo(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="photos"
    )
    picture = CloudinaryField("picture")

    def delete(self, *args, **kwargs):
        file = self.picture
        super().delete(*args, **kwargs)
        file.delete(save=False)


class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)


class Like(models.Model):
    post = models.ForeignKey(
        "Post", related_name="likes", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=["post", "user"], name="user_like_post")
        ]


class Comment(models.Model):
    post = models.ForeignKey(
        "Post", related_name="comments", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    content = models.TextField(max_length=280, blank=False)

posts/forms.py
from django import forms
from cloudinary.forms import CloudinaryFileField

from posts.models import Post, Photo, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Post
        fields = ("caption", "content")


class PhotoForm(forms.ModelForm):
    picture = CloudinaryFileField()

    class Meta:
        model = Photo
        fields = ["picture"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].options = {"tags": "photo", "format": "png"}


class PhotoFormEdit(forms.ModelForm):
    picture = CloudinaryFileField(required=False)

    class Meta:
        model = Photo
        fields = ("picture",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].options = {"tags": "photo", "format": "png"}


class HashtagForm(forms.Form):
    hashtags = forms.CharField(max_length=50, required=False)


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="comment")

    class Meta:
        model = Comment
        fields = ("content",)

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, OuterRef, Exists, Prefetch
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpRequest, JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from auths.models import User
from posts.forms import (
    PostForm,
    PhotoForm,
    PhotoFormEdit,
    HashtagForm,
    CommentForm,
)
from posts.models import Post, Photo, Like, Comment
from DjangoGramm.text_messages import (
    POST_CREATED_SUCCESS_MSG,
    POST_CREATED_DENIED_MSG,
    POST_EDIT_SUCCESS_MSG,
    CREATE_POST_SUBMIT,
    UPDATE_POST_SUBMIT,
    BAD_REQUEST,
)
from posts.utils import hashtag_handler
from posts.mixins import UserIsOwnerMixin


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/create_post.html"

    def get_success_url(self):
        return f'{reverse_lazy("posts:post_list")}?user={self.request.user.pk}'

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        if self.kwargs.get("user_id") != self.request.user.pk:
            messages.error(self.request, POST_CREATED_DENIED_MSG)
            return redirect(self.request.META.get("HTTP_REFERER", "home"))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()

        photo_form = PhotoForm(self.request.POST, self.request.FILES)
        if photo_form.is_valid():
            photo = photo_form.save(commit=False)
            photo.post = post
            photo.save()

        hashtag_form = HashtagForm(self.request.POST)
        if hashtag_form.is_valid():
            hashtags = hashtag_form.cleaned_data.get("hashtags")
            if hashtags:
                hashtag_handler(post=post, hashtags=hashtags.split())

        messages.success(self.request, POST_CREATED_SUCCESS_MSG)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["photo_form"] = PhotoForm(
                self.request.POST, self.request.FILES
            )
            context["hashtag_form"] = HashtagForm(self.request.POST)
        else:
            context["photo_form"] = PhotoForm()
            context["hashtag_form"] = HashtagForm()
            context["submit_button"] = CREATE_POST_SUBMIT
            context["title"] = "Create"
        return context


class UpdatePost(UserIsOwnerMixin, LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/edit_post.html"

    def get_success_url(self):
        return f'{reverse_lazy("posts:post_list")}?user={self.request.user.pk}'

    def form_valid(self, form):
        photo_form = PhotoForm(self.request.POST, self.request.FILES)
        if photo_form.is_valid():
            photo = photo_form.save(commit=False)
            photo.post = self.object
            photo.save()

        hashtag_form = HashtagForm(self.request.POST)
        if hashtag_form.is_valid():
            hashtags = hashtag_form.cleaned_data.get("hashtags")
            if hashtags:
                hashtag_handler(post=self.object, hashtags=hashtags.split())
        messages.success(self.request, POST_EDIT_SUCCESS_MSG)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            context["photo_form"] = PhotoFormEdit(
                self.request.POST, self.request.FILES
            )
            context["hashtag_form"] = HashtagForm(self.request.POST)
        else:
            context["photo_form"] = PhotoFormEdit()
            context["hashtag_form"] = HashtagForm()
            context["submit_button"] = UPDATE_POST_SUBMIT
            context["title"] = "Update"
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = "post"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related("user__userprofile").prefetch_related(
            "photos", "hashtags", "likes"
        )


class PostsListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = "posts"

    def _get_query_params(self):
        hashtag = self.request.GET.get("hashtag")  # type: ignore
        user_id = self.request.GET.get("user")  # type: ignore
        return hashtag, user_id

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.GET.get("user")  # type: ignore

        if user_id:
            user = get_object_or_404(User, pk=user_id)
            context["profile_user"] = user
        context["feed_name"] = "All posts"
        context["comment_form"] = CommentForm()
        return context

    def get_template_names(self):
        hashtag, user_id = self._get_query_params()
        if user_id:
            return ["posts/user_posts.html"]
        else:
            return ["posts/feed.html"]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = (
            queryset.select_related("user", "user__userprofile")
            .prefetch_related("photos", "hashtags", "likes")
            .order_by("-created_at")
        )
        likes = Like.objects.filter(user=self.request.user, post=OuterRef("pk"))
        comment_prefetch = Prefetch(
            "comments",
            queryset=Comment.objects.select_related("user__userprofile"),
        )
        queryset = queryset.prefetch_related(comment_prefetch).annotate(
            user_like_it=Exists(likes)
        )
        hashtag, user_id = self._get_query_params()
        if hashtag:
            queryset = queryset.filter(hashtags__name=hashtag)
        elif user_id:
            try:
                user_id = int(user_id)
            except ValueError as ex:
                messages.error(BAD_REQUEST, ex)
                return redirect("home")
            queryset = queryset.filter(user__id=user_id)
        return queryset


class PostsFollowingListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = "posts/feed.html"
    context_object_name = "posts"

    def _get_followed_users(self):
        return User.objects.filter(followers__follower=self.request.user)

    def get_queryset(self):
        followed_users = self._get_followed_users()
        queryset = super().get_queryset()
        queryset = (
            queryset.filter(user__in=followed_users)
            .select_related("user__userprofile")
            .prefetch_related("photos", "hashtags", "likes")
            .prefetch_related(
                Prefetch(
                    "comments",
                    queryset=Comment.objects.select_related(
                        "user__userprofile"
                    ),
                )
            )
            .annotate(
                user_like_it=Exists(
                    Like.objects.filter(
                        user=self.request.user, post=OuterRef("pk")
                    )
                )
            )
            .order_by("-created_at")
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["feed_name"] = "Following"
        return context


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = get_object_or_404(Post, pk=post_id)
            comment.save()
            return JsonResponse(
                {
                    "status": "success",
                    "message": "Comment added",
                    "username": request.user.username,
                    "comment": comment.content,
                }
            )
        else:
            return JsonResponse({"status": "error", "message": "Invalid form"})


class DeletePost(UserIsOwnerMixin, LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        return f'{reverse_lazy("posts:post_list")}?user={self.request.user.pk}'


class DeletePhoto(UserIsOwnerMixin, LoginRequiredMixin, DeleteView):
    model = Photo

    def get_success_url(self):
        return self.request.META.get("HTTP_REFERER", "home")


class LikePostView(LoginRequiredMixin, View):
    def post(self, request, pk):
        response_data = {"liked": False, "likes_count": 0}
        post = get_object_or_404(Post, pk=pk)
        try:
            like = Like.objects.get(post=post, user=request.user)
            like.delete()
            response_data["liked"] = False
        except Like.DoesNotExist:
            Like.objects.create(post=post, user=request.user)
            response_data["liked"] = True
        response_data["likes_count"] = post.likes.count()
        return JsonResponse(response_data)


class CheckLikeView(LoginRequiredMixin, View):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        response_data = {"liked": False}
        try:
            Like.objects.get(post=post, user=request.user)
            response_data["liked"] = True

        except Like.DoesNotExist:
            pass
        return JsonResponse(response_data)

posts/templates/posts/create_post.html
{% extends "base_profile.html" %}
{% load static %}
{% block main %}
    {% include "posts/includes/post_form.html" %}
{% endblock %}

posts/templates/posts/edit_post.html
{% extends "base_profile.html" %}
{% load static %}
{% block main %}
    {% for photo in post.photos.all %}
        <div>
            <img src="{% if photo.picture %}{{ photo.picture.url }}{% endif %}"
                 alt="photo" class="img-fluid"
                 style="width: 500px; height: auto;">
            <button type="button" class="btn btn-danger"
                    data-id="{{ photo.pk }}"
                    data-bs-toggle="modal" data-bs-target="#deletePhotoModal">
                <i class="fa-regular fa-trash-can"></i>
            </button>
            <div class="modal fade" id="deletePhotoModal" tabindex="-1"
                 role="dialog"
                 aria-labelledby="deletePhotoModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deletePhotoModalLabel">
                                Confirm deletion</h5>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this photo?
                        </div>
                        <div class="modal-footer">
                            <form action="{% url 'posts:delete_photo' photo.pk %}"
                                  method="post">
                                {% csrf_token %}
                                <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Cancel
                                </button>
                                <input type="submit" class="btn btn-danger"
                                       value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include "posts/includes/post_form.html" with submit_button=submit_button %}

    <button type="button" class="btn btn-danger" data-bs-toggle="modal"
            data-bs-target="#deletePostModal">
        DELETE POST
    </button>

    <div class="modal fade" id="deletePostModal" tabindex="-1" role="dialog"
         aria-labelledby="deletePostModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deletePostModalLabel">
                        Confirm deletion</h5>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this post?
                </div>
                <div class="modal-footer">
                    <form action="{% url 'posts:delete_post' post.pk %}"
                          method="post">
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary"
                                data-bs-dismiss="modal">Cancel
                        </button>
                        <input type="submit" class="btn btn-danger"
                               value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

posts/templates/posts/feed.html
{% extends "base_profile.html" %}
{% load static %}
{% block main %}
    <p class="text-center" style="font-family: 'Lobster', sans-serif; font-size: xx-large">{{ feed_name }}</p>
    {% for post in posts %}
        <div class="post-container border-bottom">
            <div class="col-12">
            <a href="{% url 'posts:post_list' %}?user={{ post.user.id }}"
               style="text-decoration: none; color: inherit;">{% include 'accounts/includes/avatar_info.html' with user=post.user %}</a>
            {% include 'posts/includes/single_post.html' %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

posts/templates/posts/photo_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Confirm deletion</h1>
        <p>Are you sure you want to delete this photo?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'posts:edit_post' pk=photo.post.pk %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Confirm deletion</h1>
        <p>Are you sure you want to delete this post?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'posts:edit_post' pk=post.pk %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base_profile.html" %}
{% load static %}
{% block main %}
    <div class="container-fluid mx-auto">
        <h6>{{ post.caption }}</h6>

        <div id="postPhotosCarousel" class="carousel slide" style="background-color: #3b3e3d"
             data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for photo in post.photos.all %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img src="{{ photo.picture.url }}" class="carousel-photo"
                             alt="">
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button"
                    data-bs-target="#postPhotosCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"
                      aria-hidden="true"></span>
                <span class="visually-hidden">Prev</span>
            </button>
            <button class="carousel-control-next" type="button"
                    data-bs-target="#postPhotosCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon"
                      aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>

        <p>{{ post.content }}</p>
        <p>{{ post.likes.count }} likes</p>
        <h6>Likes from:</h6>
        {% for like in post.likes.all %}
            <div class="row">
                <a class="text-left"
                   href="{% url 'posts:post_list' %}?user={{ like.user.id }}">
                    {% include 'accounts/includes/avatar_info.html' with user=like.user %}
                </a>
            </div>
        {% endfor %}
        {% for hashtag in post.hashtags.all %}
            <a href="{% url 'posts:post_list' %}?hashtag={{ hashtag.name }}">
                <span class="hashtag">#{{ hashtag.name }}</span>
            </a>
        {% endfor %}
        <div>
            {% if post.user == request.user %}
                <a href="{% url 'posts:edit_post' post.id %}"
                   class="btn btn-lg custom-btn me-2">
                    <i class="fa-solid fa-gear"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

posts/templates/posts/posts_of_user.html
{% extends "base_profile.html" %}
{% load static %}
{% block main %}
    {% for post in user.posts.all %}
        <div class="center">
            <div class="post">
                <div class="image-container">
                    {% for photo in post.photos.all %}
                        <img src="{{ photo.picture.url }}" alt="Photo">
                    {% endfor %}
                </div>
                <a href="{% url 'posts:edit_post' post.id %}">
                    <p>{{ post.caption }}</p></a>
                {% for hashtag in post.hashtags.all %}
                    <span class="hashtag">#{{ hashtag.name }}</span>
                {% endfor %}
                <p>{{ post.likes.count }} likes</p>
                <button class="button"><a
                        href="{% url 'posts:like_post' post.id %}">Like</a>
                </button>
                <button class="button">
                    <a href="{% url 'posts:edit_post' post.id %}">Edit</a>
                </button>
            </div>
        </div>
    {% endfor %}

{% endblock %}

posts/templates/posts/user_posts.html
{% extends "base_profile.html" %}
{% load static %}
{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="d-flex align-items-center justify-content-center">
                <img
                        src="{% if profile_user.userprofile.avatar %}
                        {{ profile_user.userprofile.avatar.url }}
                        {% else %}{% static 'images/no_avatar.jpg' %}
                        {% endif %}"
                        alt=""
                        class="rounded-circle p-3"
                        style="width: 100px; height: 100px;">
                <h4 class="text-center">{{ profile_user }}</h4>
                {% if profile_user.pk != user.pk %}
                    <button type="button" data-id="{{ profile_user.pk }}"
                            class="follow-btn ms-3"><i
                            class="fa-regular fa-circle-check"></i>
                    </button>
                {% endif %}
            </div>
            {% if profile_user.userprofile.bio %}
                <div class="d-flex align-items-center justify-content-center mb-5">
                    <div id="short_bio"><b>About
                        me: </b>{{ profile_user.userprofile.bio|slice:":100"|linebreaksbr}}...
                    </div>
                    <div id="full_bio"
                         style="display:none;"><b>About
                        me: </b>{{ profile_user.userprofile.bio|linebreaksbr }}</div>
                    <button type="button" class="btn"
                            onclick="toggleBio()"><i id="toggleIcon"
                                                     class="fa-solid fa-caret-down"></i>
                    </button>
                </div>
            {% endif %}
            {% if posts|length > 0 %}
                {% for post in posts %}
                    <div class="col-sm-12 col-md-6 col-lg-4"
                         style="max-width: 575px">
                        {% include 'posts/includes/single_post.html' %}
                    </div>
                {% endfor %}
            {% else %}
                <h5 class="text-center mt-5">no posts yet <i
                        class="fa-regular fa-face-frown-open ms-2"
                        style="font-size: x-large"></i></h5>
            {% endif %}
        </div>
    </div>

{% endblock %}